local global = require("global")
local utils = require("utils")
local opt = utils.opt

local global_options = {
  termguicolors = true,
  mouse = "nv",
  errorbells = true,
  visualbell = true,
  hidden = true,
  fileformats = "unix,mac,dos",
  magic = true,
  virtualedit = "block",
  encoding = "utf-8",
  viewoptions = "folds,cursor,curdir,slash,unix",
  sessionoptions = "curdir,help,tabpages,winsize",
  clipboard = "unnamedplus",
  wildignorecase = true,
  wildignore = ".git,.hg,.svn,*.pyc,*.o,*.out,*.jpg,*.jpeg,*.png,*.gif,*.zip,**/tmp/**,*.DS_Store,**/node_modules/**,**/bower_modules/**",
  backup = false,
  writebackup = false,
  undofile = true,
  swapfile = false,
  directory = global.cache_dir .. "swag/",
  undodir = global.cache_dir .. "undo/",
  backupdir = global.cache_dir .. "backup/",
  viewdir = global.cache_dir .. "view/",
  spellfile = global.cache_dir .. "spell/en.uft-8.add",
  history = 2000,
  shada = "!,'300,<50,@100,s10,h",
  backupskip = "/tmp/*,$TMPDIR/*,$TMP/*,$TEMP/*,*/shm/*,/private/var/*,.vault.vim",
  smarttab = true,
  shiftround = true,
  timeout = true,
  ttimeout = true,
  timeoutlen = 500,
  ttimeoutlen = 10,
  updatetime = 100,
  redrawtime = 1500,
  ignorecase = true,
  smartcase = true,
  infercase = true,
  incsearch = true,
  wrapscan = true,
  complete = ".,w,b,k",
  inccommand = "nosplit",
  grepformat = "%f:%l:%c:%m",
  grepprg = "rg --hidden --vimgrep --smart-case --",
  breakat = [[\ \	;:,!?]],
  startofline = false,
  whichwrap = "h,l,<,>,[,],~",
  splitbelow = true,
  splitright = true,
  switchbuf = "useopen",
  backspace = "indent,eol,start",
  diffopt = "filler,iwhite,internal,algorithm:patience",
  completeopt = "menuone,noselect",
  jumpoptions = "stack",
  showmode = false,
  shortmess = "aoOTIcF",
  scrolloff = 2,
  sidescrolloff = 5,
  foldlevelstart = 99,
  ruler = false,
  list = true,
  showtabline = 2,
  winwidth = 30,
  winminwidth = 10,
  pumheight = 15,
  helpheight = 12,
  previewheight = 12,
  showcmd = false,
  cmdheight = 2,
  cmdwinheight = 5,
  equalalways = false,
  laststatus = 2,
  display = "lastline",
  showbreak = "↳  ",
  listchars = "tab:»·,nbsp:+,trail:·,extends:→,precedes:←",
  pumblend = 10,
  winblend = 10,
}
local buffer_options = {
  synmaxcol = 2500,
  formatoptions = "1jcroql",
  textwidth = 80,
  expandtab = true,
  autoindent = true,
  tabstop = 2,
  shiftwidth = 2,
  softtabstop = -1,
}
local window_options = {
  number = true,
  relativenumber = true,
  colorcolumn = "80",
  signcolumn = "yes",
  wrap = false,
  linebreak = true,
  breakindentopt = "shift:2,min:20",
  foldenable = true,
  conceallevel = 2,
  concealcursor = "niv",
}

for name, value in pairs(global_options) do
  opt(name, value)
end

for name, value in pairs(buffer_options) do
  opt(name, value, { vim.o, vim.bo })
end

for name, value in pairs(window_options) do
  opt(name, value, { vim.o, vim.wo })
end
