require("lspkind").init({
  with_text = false,
  symbol_map = {
    Text = "",
    Method = "",
    Function = "ƒ",
    Constructor = "",
    Variable = "",
    Class = "",
    Interface = "",
    Module = "",
    Property = "",
    Unit = "",
    Value = "",
    Enum = "",
    Keyword = "",
    Snippet = "",
    Color = "",
    File = "",
    Folder = "",
    EnumMember = "",
    Constant = "",
    Struct = "פּ",
  },
})
